spring.application.name=Streakify
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/streakify_db
spring.datasource.username=postgres
spring.datasource.password=your_password


# JPA Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

